# Generated by Django 5.1.15 on 2026-03-14 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('investment_received', 'Investment Received'), ('investment_confirmed', 'Investment Confirmed'), ('campaign_update', 'Campaign Update'), ('campaign_approved', 'Campaign Approved'), ('campaign_rejected', 'Campaign Rejected'), ('milestone_completed', 'Milestone Completed'), ('startup_approved', 'Startup Approved'), ('new_message', 'New Message'), ('new_follower', 'New Follower'), ('task_assigned', 'Task Assigned'), ('task_comment', 'Task Comment')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('related_object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='users.userprofile')),
                ('related_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='idx_notif_recipient_unread')],
            },
        ),
    ]
