# Generated by Django 5.1.15 on 2026-03-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('investment_received', 'Investment Received'), ('investment_confirmed', 'Investment Confirmed'), ('campaign_update', 'Campaign Update'), ('campaign_approved', 'Campaign Approved'), ('campaign_rejected', 'Campaign Rejected'), ('milestone_completed', 'Milestone Completed'), ('startup_approved', 'Startup Approved'), ('new_message', 'New Message'), ('new_follower', 'New Follower'), ('task_assigned', 'Task Assigned'), ('task_comment', 'Task Comment'), ('user_approved', 'User Approved'), ('user_rejected', 'User Rejected')], max_length=30),
        ),
    ]
