# Generated by Django 5.1.15 on 2026-03-14 16:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('avatar_url', models.URLField(blank=True, default='', max_length=500)),
                ('role', models.CharField(choices=[('founder', 'Founder'), ('team_member', 'Team Member'), ('investor', 'Investor'), ('admin', 'Admin')], default='investor', max_length=20)),
                ('bio', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
