# Generated by Django 5.1.15 on 2026-03-15 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role_selected',
            field=models.BooleanField(default=False),
        ),
    ]
