# Generated by Django 5.1.15 on 2026-03-18 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_role_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='company',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='job_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='InvestorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_industries', models.JSONField(blank=True, default=list)),
                ('check_size_min', models.IntegerField(blank=True, null=True)),
                ('check_size_max', models.IntegerField(blank=True, null=True)),
                ('preferred_stage', models.CharField(blank=True, choices=[('pre_seed', 'Pre-Seed'), ('seed', 'Seed'), ('series_a', 'Series A'), ('series_b_plus', 'Series B+')], default='', max_length=20)),
                ('accreditation_status', models.CharField(blank=True, choices=[('accredited', 'Accredited'), ('non_accredited', 'Non-Accredited'), ('prefer_not_to_say', 'Prefer Not to Say')], default='', max_length=20)),
                ('accreditation_description', models.TextField(blank=True, default='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investor_profile', to='users.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
