# Generated by Django 5.1.15 on 2026-03-18 23:56

from django.db import migrations


def backfill_onboarding_completed(apps, schema_editor):
    UserProfile = apps.get_model("users", "UserProfile")
    UserProfile.objects.filter(role_selected=True).update(onboarding_completed=True)


def reverse_backfill(apps, schema_editor):
    UserProfile = apps.get_model("users", "UserProfile")
    UserProfile.objects.filter(onboarding_completed=True).update(onboarding_completed=False)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_company_userprofile_job_title_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_onboarding_completed, reverse_backfill),
    ]
