# Generated by Django 5.1.15 on 2026-03-19 12:17

from django.db import migrations


def backfill_approval(apps, schema_editor):
    UserProfile = apps.get_model("users", "UserProfile")
    UserProfile.objects.filter(onboarding_completed=True).update(
        approval_status="approved"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_userprofile_approval_status_and_more"),
    ]

    operations = [
        migrations.RunPython(backfill_approval, migrations.RunPython.noop),
    ]
