# Generated by Django 5.1.15 on 2026-05-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_backfill_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='company_document_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='id_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='identity_document_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
