# Generated by Django 5.1.15 on 2026-05-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0002_startupinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='legal_form',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='startup',
            name='registration_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
