# Generated by Django 5.1.15 on 2026-05-01 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copilot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='copilotmessage',
            name='media_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='copilotmessage',
            name='media_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='copilotmessage',
            name='thinking_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='copilotmessage',
            name='thinking_duration',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
